version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests with JUnit as reporter
          command: npm test -- --ci --coverage --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
